export const demoPassword = "Password123!";

export const skillTags = [
  "React",
  "Node.js",
  "Prisma",
  "MariaDB",
  "UI Design",
  "Copywriting",
  "Photography",
  "Video Editing",
  "Tutoring",
  "Excel",
  "Data Analysis",
  "Translation",
  "Dog Walking",
  "Cleaning",
  "Event Planning",
  "Personal Training",
  "Graphic Design",
  "Social Media",
  "Bike Repair",
  "Music Lessons",
  "Frontend",
  "Backend",
  "Figma",
  "SEO"
];

export const users = [
  {
    email: "ava.lind@sidequest.dev",
    firstName: "Ava",
    lastName: "Lind",
    role: "TALENT",
    headline: "Frontend developer for polished landing pages",
    bio: "I build clean React interfaces for students, clubs, and small businesses that need a professional web presence.",
    location: "Stockholm",
    hourlyRateCents: 42000,
    availability: "Weekday evenings",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    skillTags: ["React", "Frontend", "UI Design", "Figma"]
  },
  {
    email: "noah.berg@sidequest.dev",
    firstName: "Noah",
    lastName: "Berg",
    role: "TALENT",
    headline: "Backend helper for APIs and databases",
    bio: "I help teams set up Express APIs, Prisma models, and database workflows that are easy to understand.",
    location: "Gothenburg",
    hourlyRateCents: 45000,
    availability: "Weekends",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
    skillTags: ["Node.js", "Backend", "Prisma", "MariaDB"]
  },
  {
    email: "maya.ali@sidequest.dev",
    firstName: "Maya",
    lastName: "Ali",
    role: "TALENT",
    headline: "Photographer for portraits and local events",
    bio: "I shoot natural portraits, graduation photos, and small event galleries with quick turnaround.",
    location: "Malmo",
    hourlyRateCents: 38000,
    availability: "Friday to Sunday",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
    skillTags: ["Photography", "Event Planning", "Social Media"]
  },
  {
    email: "leo.svensson@sidequest.dev",
    firstName: "Leo",
    lastName: "Svensson",
    role: "TALENT",
    headline: "Math and programming tutor",
    bio: "I tutor high school and first-year university students in math, JavaScript, and study planning.",
    location: "Uppsala",
    hourlyRateCents: 30000,
    availability: "After school",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
    skillTags: ["Tutoring", "React", "Data Analysis"]
  },
  {
    email: "ella.nguyen@sidequest.dev",
    firstName: "Ella",
    lastName: "Nguyen",
    role: "TALENT",
    headline: "Social media content and short-form video",
    bio: "I plan, film, and edit short-form videos for cafes, student groups, and independent creators.",
    location: "Stockholm",
    hourlyRateCents: 33000,
    availability: "Flexible",
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1",
    skillTags: ["Video Editing", "Social Media", "Copywriting"]
  },
  {
    email: "oscar.holm@sidequest.dev",
    firstName: "Oscar",
    lastName: "Holm",
    role: "TALENT",
    headline: "Bike repair and maintenance",
    bio: "I fix flat tires, adjust brakes, tune gears, and help people keep their bikes commuter-ready.",
    location: "Lund",
    hourlyRateCents: 26000,
    availability: "Saturday mornings",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d",
    skillTags: ["Bike Repair"]
  },
  {
    email: "sara.martin@sidequest.dev",
    firstName: "Sara",
    lastName: "Martin",
    role: "TALENT",
    headline: "English, Swedish, and French translation",
    bio: "I translate short documents, product copy, menus, and student project material with careful tone matching.",
    location: "Stockholm",
    hourlyRateCents: 31000,
    availability: "Remote",
    avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80",
    skillTags: ["Translation", "Copywriting", "SEO"]
  },
  {
    email: "amir.khan@sidequest.dev",
    firstName: "Amir",
    lastName: "Khan",
    role: "TALENT",
    headline: "Personal trainer for beginner-friendly routines",
    bio: "I make simple training plans for people getting back into movement, strength, and consistency.",
    location: "Gothenburg",
    hourlyRateCents: 36000,
    availability: "Early mornings",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
    skillTags: ["Personal Training"]
  },
  {
    email: "linnea.ek@sidequest.dev",
    firstName: "Linnea",
    lastName: "Ek",
    role: "TALENT",
    headline: "Graphic designer for posters and brand kits",
    bio: "I create posters, social assets, and small visual identity kits for student organizations and local projects.",
    location: "Umea",
    hourlyRateCents: 34000,
    availability: "Weekday afternoons",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2",
    skillTags: ["Graphic Design", "Figma", "Social Media"]
  },
  {
    email: "jonas.pettersson@sidequest.dev",
    firstName: "Jonas",
    lastName: "Pettersson",
    role: "TALENT",
    headline: "Spreadsheet cleanup and dashboard helper",
    bio: "I turn messy spreadsheets into readable tables, charts, and lightweight reports.",
    location: "Linkoping",
    hourlyRateCents: 28000,
    availability: "Remote evenings",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
    skillTags: ["Excel", "Data Analysis"]
  },
  {
    email: "nora.wilson@sidequest.dev",
    firstName: "Nora",
    lastName: "Wilson",
    role: "TALENT",
    headline: "Piano and beginner music lessons",
    bio: "I teach beginner piano, music reading, and practice routines for kids and adults.",
    location: "Stockholm",
    hourlyRateCents: 32000,
    availability: "Sundays",
    avatarUrl: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c",
    skillTags: ["Music Lessons", "Tutoring"]
  },
  {
    email: "felix.andersson@sidequest.dev",
    firstName: "Felix",
    lastName: "Andersson",
    role: "TALENT",
    headline: "Reliable cleaning and move-out help",
    bio: "I help with apartment cleaning, packing support, and practical move-out checklists.",
    location: "Malmo",
    hourlyRateCents: 24000,
    availability: "Weekends",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
    skillTags: ["Cleaning"]
  },
  {
    email: "isabella.rossi@sidequest.dev",
    firstName: "Isabella",
    lastName: "Rossi",
    role: "TALENT",
    headline: "Dog walking and pet check-ins",
    bio: "I walk dogs, refill food and water, and send quick photo updates while owners are away.",
    location: "Stockholm",
    hourlyRateCents: 22000,
    availability: "Lunch breaks",
    avatarUrl: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb",
    skillTags: ["Dog Walking"]
  },
  {
    email: "victor.chen@sidequest.dev",
    firstName: "Victor",
    lastName: "Chen",
    role: "TALENT",
    headline: "SEO and web copy for small sites",
    bio: "I rewrite homepages, service pages, and product descriptions so they are clearer and easier to find.",
    location: "Remote",
    hourlyRateCents: 35000,
    availability: "Remote",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
    skillTags: ["SEO", "Copywriting"]
  },
  {
    email: "emma.johansson@sidequest.dev",
    firstName: "Emma",
    lastName: "Johansson",
    role: "CLIENT",
    headline: "Student founder looking for creative support",
    bio: "I post tasks for design, content, and launch support for student-led projects.",
    location: "Stockholm",
    hourlyRateCents: null,
    availability: "Project-based",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    skillTags: ["Event Planning", "Social Media"]
  },
  {
    email: "miles.brown@sidequest.dev",
    firstName: "Miles",
    lastName: "Brown",
    role: "CLIENT",
    headline: "Small business owner hiring local help",
    bio: "I use SideQuest to find people for product photos, copy, and quick web updates.",
    location: "Gothenburg",
    hourlyRateCents: null,
    availability: "Monthly projects",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
    skillTags: ["Photography", "Copywriting", "Frontend"]
  },
  {
    email: "admin@sidequest.dev",
    firstName: "SideQuest",
    lastName: "Admin",
    role: "ADMIN",
    headline: "Platform admin account",
    bio: "Demo admin profile for reviewing platform flows and moderation screens.",
    location: "Remote",
    hourlyRateCents: null,
    availability: "Internal",
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7",
    skillTags: ["Backend", "Data Analysis"]
  },
  {
    email: "olivia.green@sidequest.dev",
    firstName: "Olivia",
    lastName: "Green",
    role: "CLIENT",
    headline: "Event organizer hiring flexible helpers",
    bio: "I organize small local events and hire help for setup, photos, and social content.",
    location: "Uppsala",
    hourlyRateCents: null,
    availability: "Seasonal",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
    skillTags: ["Event Planning", "Photography", "Social Media"]
  }
];
